/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.8 */

#ifndef PB_PB_MEASUREMENTS_PB_H_INCLUDED
#define PB_PB_MEASUREMENTS_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _pb_Measurements {
    int32_t chipID;
    float soilMoisture;
    float temperature;
    float humidity;
    float pressure;
    float altitude;
} pb_Measurements;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define pb_Measurements_init_default             {0, 0, 0, 0, 0, 0}
#define pb_Measurements_init_zero                {0, 0, 0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define pb_Measurements_chipID_tag               1
#define pb_Measurements_soilMoisture_tag         2
#define pb_Measurements_temperature_tag          3
#define pb_Measurements_humidity_tag             4
#define pb_Measurements_pressure_tag             5
#define pb_Measurements_altitude_tag             6

/* Struct field encoding specification for nanopb */
#define pb_Measurements_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    chipID,            1) \
X(a, STATIC,   SINGULAR, FLOAT,    soilMoisture,      2) \
X(a, STATIC,   SINGULAR, FLOAT,    temperature,       3) \
X(a, STATIC,   SINGULAR, FLOAT,    humidity,          4) \
X(a, STATIC,   SINGULAR, FLOAT,    pressure,          5) \
X(a, STATIC,   SINGULAR, FLOAT,    altitude,          6)
#define pb_Measurements_CALLBACK NULL
#define pb_Measurements_DEFAULT NULL

extern const pb_msgdesc_t pb_Measurements_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define pb_Measurements_fields &pb_Measurements_msg

/* Maximum encoded size of messages (where known) */
#define PB_MEASUREMENTS_PB_H_MAX_SIZE            pb_Measurements_size
#define pb_Measurements_size                     36

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
